apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pc76vhawn-go 
  janus-idp.io/tekton: pc76vhawn-go
  backstage.io/kubernetes-id: pc76vhawn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pc76vhawn-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml